#!/bin/sh

revision="VIM v0.1.0 (2020-11-16 by MIBonk)"
# use --help for more info

export PATH=:/proc/boot:/sbin:/bin:/usr/bin:/usr/sbin:/net/mmx/bin:/net/mmx/usr/bin:/net/mmx/usr/sbin:/net/mmx/sbin:/net/mmx/mnt/app/armle/bin:/net/mmx/mnt/app/armle/sbin:/net/mmx/mnt/app/armle/usr/bin:/net/mmx/mnt/app/armle/usr/sbin
export LD_LIBRARY_PATH=/net/mmx/mnt/app/root/lib-target:/net/mmx/mnt/eso/lib:/net/mmx/eso/lib:/net/mmx/mnt/app/usr/lib:/net/mmx/mnt/app/armle/lib:/net/mmx/mnt/app/armle/lib/dll:/net/mmx/mnt/app/armle/usr/lib
export IPL_CONFIG_DIR=/etc/eso/production

thisname="$(basename $0)"
thisdir="$(dirname $0)"

if [ ! -z $2 ]; then
VALUE=patch
else
VALUE=""
fi

	case $VALUE in

	patch) {

if [ -z $LOG ]; then
	. $thisdir/../config/GLOBALS
	echo -ne "\n$ME-$thisname---->\n" >> $LOG
fi

if [ ! -z $VIM 2>/dev/null ]; then
	echo -ne "VIM on Unit: "$VIM"\n\n" >> $LOG
	POSITION=$1
	HEXVALUE=$2
	if [ $(echo $HEXVALUE | wc -c) -eq 3 ] ; then	
		HEXVALUE=$(echo $HEXVALUE | awk '{print toupper($0)}') 
		VIM=$(echo $VIM | cut -c1-56)
		LENGTH=$(echo $VIM | wc -c)
		LENGTH=$(echo $LENGTH -3 | bc)
		if [ $POSITION -le $LENGTH ] && [ $(( $POSITION % 2 )) -eq 0 ]; then
			if [ $POSITION -ge "2" ]; then
				PRI=$(echo $VIM | cut -c1-$POSITION)
			else
			PRE=""
			fi
			if [ $POSITION -ne $LENGTH ]; then
				POSITION=$(echo $POSITION +3 | bc)
				SEC=$(echo $VIM | cut -c$POSITION-$(echo $LENGTH +2 | bc))
			else
				SEC=""
			fi
			VIMPATCH=$PRI$HEXVALUE$SEC
			. $thisdir/crc16 $VIMPATCH
			VIMPATCH=$VIMPATCH$crcsum
			on -f mmx /net/mmx/eso/bin/apps/pc b:0:3221422082 $VIMPATCH 2>> $LOG
			DEZ=$(echo "ibase=16; $HEXVALUE" | bc)
			echo -ne "VIM is now patched on Byte $1 with $DEZ km/h (0x$HEXVALUE)\n\n" | tee -a $LOG
			. $thisdir/reboot -t 10
			exit 0
		else
			echo -ne "Wrong Position\n\n"
		fi
	else	
		echo -ne "no binary hex digits in Value\n\n"
	fi
else
	echo -ne "There is no Flashpart for VIM!\n\n" | tee -a $LOG
fi

return 2> /dev/null

	};;

	# help or unknown parameter ------------------------------
	*) {
		echo ""
		echo $revision
		echo ""
		echo "Usage: "$thisname" [OPTION]"
		echo ""
		echo "Options:"
		echo "        <POSITION> <VALUE> 	Position HEX"
		echo "        --help			show this help"
		echo ""
		echo "This program is free software; you can redistribute it and/or"
		echo "modify it under the terms of the GNU General Public License"
		echo "as published by the Free Software Foundation; either version 2"
		echo "of the License, or (at your option) any later version."
		echo ""
		echo "This program is distributed in the hope that it will be useful,"
		echo "but WITHOUT ANY WARRANTY; without even the implied warranty of"
		echo "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."
		echo "See the GNU General Public License for more details."
		echo ""
		echo "You should have received a copy of the GNU General Public License"
		echo "along with this program; if not, write to the Free Software Foundation,"
		echo "Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA."
		echo ""
		
	};;

	esac

exit 0

